export const mockDatabases = [
  {
    id: 1,
    name: 'ecommerce_db',
    charset: 'utf8mb4',
    tablesCount: 45,
    size: '256 MB',
    status: 'Active',
    createdAt: '2026-01-15',
  },
  {
    id: 2,
    name: 'user_auth_db',
    charset: 'utf8mb4',
    tablesCount: 12,
    size: '48 MB',
    status: 'Active',
    createdAt: '2026-02-01',
  },
  {
    id: 3,
    name: 'analytics_logs',
    charset: 'utf8',
    tablesCount: 88,
    size: '1.2 GB',
    status: 'Maintenance',
    createdAt: '2025-11-20',
  },
  {
    id: 4,
    name: 'payment_gateway',
    charset: 'utf8mb4',
    tablesCount: 24,
    size: '512 MB',
    status: 'Active',
    createdAt: '2026-03-10',
  },
  {
    id: 5,
    name: 'crm_system',
    charset: 'latin1',
    tablesCount: 30,
    size: '180 MB',
    status: 'Inactive',
    createdAt: '2025-08-05',
  },
  {
    id: 6,
    name: 'inventory_db',
    charset: 'utf8mb4',
    tablesCount: 19,
    size: '95 MB',
    status: 'Active',
    createdAt: '2026-04-12',
  },
  {
    id: 7,
    name: 'notification_service',
    charset: 'utf8mb4',
    tablesCount: 8,
    size: '22 MB',
    status: 'Active',
    createdAt: '2026-05-01',
  },
  {
    id: 8,
    name: 'test_sandbox',
    charset: 'utf8',
    tablesCount: 5,
    size: '10 MB',
    status: 'Inactive',
    createdAt: '2026-06-18',
  },
];
