export const mockColumns = [
  {
    id: 1,
    tableId: 1,
    name: 'id',
    type: 'INT',
    isPrimaryKey: true,
    isNullable: false,
    defaultValue: null,
    isAutoIncrement: true,
  },
  {
    id: 2,
    tableId: 1,
    name: 'username',
    type: 'VARCHAR(255)',
    isPrimaryKey: false,
    isNullable: false,
    defaultValue: null,
    isAutoIncrement: false,
  },
  {
    id: 3,
    tableId: 1,
    name: 'email',
    type: 'VARCHAR(255)',
    isPrimaryKey: false,
    isNullable: false,
    defaultValue: null,
    isAutoIncrement: false,
  },
  {
    id: 4,
    tableId: 1,
    name: 'is_active',
    type: 'BOOLEAN',
    isPrimaryKey: false,
    isNullable: false,
    defaultValue: 'true',
    isAutoIncrement: false,
  },
  {
    id: 5,
    tableId: 1,
    name: 'created_at',
    type: 'DATETIME',
    isPrimaryKey: false,
    isNullable: true,
    defaultValue: 'CURRENT_TIMESTAMP',
    isAutoIncrement: false,
  },
];
