export const mockTables = [
  {
    id: 1,
    databaseId: 1,
    name: 'users',
    engine: 'InnoDB',
    rowsCount: 1420,
    size: '128 KB',
    createdAt: '2026-01-16',
  },
  {
    id: 2,
    databaseId: 1,
    name: 'orders',
    engine: 'InnoDB',
    rowsCount: 8530,
    size: '2.4 MB',
    createdAt: '2026-01-20',
  },
  {
    id: 3,
    databaseId: 1,
    name: 'products',
    engine: 'InnoDB',
    rowsCount: 450,
    size: '64 KB',
    createdAt: '2026-02-05',
  },
  {
    id: 4,
    databaseId: 2,
    name: 'auth_tokens',
    engine: 'Memory',
    rowsCount: 95,
    size: '16 KB',
    createdAt: '2026-02-02',
  },
  {
    id: 5,
    databaseId: 2,
    name: 'permissions',
    engine: 'InnoDB',
    rowsCount: 32,
    size: '8 KB',
    createdAt: '2026-02-03',
  },
];
